### ISSUE TITLE
Continuous Fine-tuning Bunny 1.1 4B

### ISSUE THREAD

**Issue by ChenFicha** [BAAI-DCAI/Bunny#123]
I am continous fine-tuning Bunny 1.1 4B. I have a question about the training codes.

In train.py, when calling `model.get_model().initialize_vision_modules(model_args=model_args)`, does it load the vision tower's weights from google/siglip-so400m-patch14-384 instead of from Bunny's weights? Since it is called after `BunnyPhi3ForCausalLM.from_pretrained()`, seem it would override the Bunny's vision tower weight.

**Comment by Isaachhh** [comment]
In continuous fine-tuning, I think the weights of vision tower would be loaded from Bunny instead of original siglip [here](https://github.com/BAAI-DCAI/Bunny/blob/main/bunny/model/bunny_arch.py#L17).

What about you print some tensors of vision tower before and after calling `model.get_model().initialize_vision_modules(model_args=model_args)`?

**Comment by Isaachhh** [comment]
What if you add
```
if self.is_loaded:
    return
```

[here](https://github.com/BAAI-DCAI/Bunny/blob/main/bunny/model/multimodal_encoder/siglip/siglip_encoder.py#L22)?

**Comment by Isaachhh** [comment]
Thank you so much for pointing out this bug!
